menu:
  Home: /
  About: /about
  RSS: /atom.xml

vertical: false
excerpt: true
darkmode: true
always_darkmode: false
podcast: false
favicon: favicon.png
license: 本站文章使用CC BY-SA 4.0许可。
#font_mirror: fonts.loli.net // 国内更快
font_mirror: fonts.googleapis.com
custom_fonts:
to_chinese_date: true
