menu:
  Home: /
  About: /about
  RSS: /atom.xml

vertical: false
excerpt: true
darkmode: true
always_darkmode: false
podcast: false
favicon: favicon.png
license: 本站文章使用 [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) 许可。
#font_mirror: fonts.loli.net // 国内更快
font_mirror: fonts.googleapis.com
custom_fonts:
to_chinese_date: true
